development:
  adapter:   mysql
  database:  Toopaste
  username:  user
  password:  password
  host:      localhost

production:
  adapter:   mysql
  database:  Toopaste
  username:  user
  password:  password
  host:      localhost
  
test:
    adapter:   sqlite
    database:  :memory: